apiVersion: v1
kind: Pod
metadata:
  name: malicious-privileged
  labels:
    test: malicious
    category: privilege_escalation
spec:
  containers:
  - name: attacker
    image: alpine:3.19
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      privileged: true
