apiVersion: v1
kind: Pod
metadata:
  name: python-app-secure
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
  containers:
  - name: app
    image: python:3.11-slim
    command: ["python3", "-m", "http.server", "8000"]
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
