apiVersion: v1
kind: Pod
metadata:
  name: redis-secure
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
  containers:
  - name: redis
    image: redis:7-alpine
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
